# This is the sample configuration file for Nebula.
# You must edit at least the static_host_map, lighthouse, and firewall sections.

# Basic terminology:
# Node: a host that participates in the Nebula network. This can be a server,
#       virtual machine, laptop, mobile phone, or any other capable host.
# Routable IP: a node's "normal" or "native" IP address. This is typically a
#              static public IP address for a server. For a laptop or mobile
#              device, this is typically a dynamic IP address assigned by DHCP.
#              If the node is behind a NAT, this is the external IP address of
#              the NAT gateway.
# Nebula IP: a node's "VPN" IP address. This is the IP address that nodes use to
#            communicate within the Nebula network. This address is baked
#            directly into the node's certificate file.

# Some options in this file, including the pki section, can be reloaded
# without affecting existing tunnels.
# To reload, send a HUP to the nebula process.

# PKI defines the location of credentials for this node.
# Each of these can also be inlined by using the yaml ": |" syntax.
pki:
  # Path to a file containing one or more CA certificates that will be accepted
  # by this node. The certificates must all be created by 'nebula-cert ca'.
  ca: /etc/nebula/ca.crt
  # cert: path to this node's certificate file
  # key: path to this node's private key file
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

  # List of certificate fingerprints that we will refuse to talk to
  #blocklist:
  #  - c99d4e650533b92061b09918e838a5a0a6aaee21eed1d12fd937682865936c72

  # Force disconnect a client if their certificate is expired or invalid.
  # Default is false
  #disconnect_invalid: false


# The static host map defines a set of known hosts with static IP addresses.
# Each entry maps a node's Nebula IP address to its routable IP addresses.
# If a node has multiple routable IP addresses, nebula will try each one when
# establishing a tunnel.
# The syntax is:
#   "{nebula ip}": ["{routable ip/dns name}:{routable port}"]
static_host_map:
  # Example: lighthouse with Nebula IP of 192.168.100.1 and routable IP address
  #          of 100.64.22.11, with nebula listening on port 4242
  "192.168.100.1": ["100.64.22.11:4242"]
  # Example: map a nebula node to a domain name
  #"192.168.100.2": ["nebula.example.com:4242"]
  # Example: a host with multiple IP addresses
  #"192.168.100.3": ["107.63.148.70:4242", "136.144.110.48:4242"]


lighthouse:
  # Enable lighthouse functionality for this node.
  # Default is false
  am_lighthouse: false

  # Start a simple DNS server.
  # Default is false
  #serve_dns: false
  #dns:
    # Host and port that the DNS server listens at.
    # This can be a routable IP or a Nebula node IP.
    #host: 0.0.0.0
    #port: 53

  # The number of seconds between updates from this node to a lighthouse.
  # During updates, a node sends information about its current IP addresses
  # to each lighthouse.
  # Default is 10 seconds
  interval: 60

  # List of lighthouse hosts this node should report to and query from.
  # IMPORTANT: THIS SHOULD BE EMPTY ON LIGHTHOUSE NODES
  # IMPORTANT2: THIS SHOULD BE LIGHTHOUSES' NEBULA IPs, NOT THEIR ROUTABLE IPs
  hosts:
    - "192.168.100.1"
    - "192.168.100.5"

  # List of allowed routable IP ranges for remote nodes. This list is checked
  # during handshake. If not specified, all IP ranges are allowed.
  # You can provide CIDRs here with `true` to allow and `false` to deny.
  # The most specific CIDR rule applies to each remote.
  # If all rules are "allow", the default will be "deny", and vice-versa.
  # If both "allow" and "deny" rules are present, then you MUST set a rule
  # for "0.0.0.0/0" as the default.
  #remote_allow_list:
    # Example: block IPs in this subnet from connecting to this node.
    #"172.16.0.0/12": false

    # A more complicated example: allow public IPs, but allow only private IPs
    # from a specific subnet (10.42.42.0/24).
    #"0.0.0.0/0": true
    #"10.0.0.0/8": false
    #"10.42.42.0/24": true

  # EXPERIMENTAL: This option my change or disappear in the future.
  # Define the equivalent of remote_allow_list blocks, but for each specific
  # Nebula VPN IP range. Each VPN IP range can have its own list of allowable
  # routable IP ranges.
  #remote_allow_ranges:
    # Example: for Nebula VPN IP addresses in 10.42.42.0/24, allow nodes to have
    # routable IP addresses in the 192.168.0.0/16 range.
    #"10.42.42.0/24":
      #"192.168.0.0/16": true
    # Example: for Nebula IP addresses within 10.42.41.0/24, allow nodes to join
    # from the 123.45.0.0/16 range.
    #"10.42.41.0/24":
      #"123.45.0.0/16": true

  # local_allow_list allows you to filter which local IP addresses we advertise
  # to the lighthouses. This uses the same logic as `remote_allow_list`, but
  # additionally, you can specify an `interfaces` map of regular expressions
  # to match against interface names. The regexp must match the entire name.
  # All interface rules must be either true or false (and the default will be
  # the inverse). CIDR rules are matched after interface name rules.
  # Default is all local IP addresses
  #local_allow_list:
    # Example to block tun0 and all docker interfaces.
    #interfaces:
      #tun0: false
      #'docker.*': false
    # Example to only advertise this subnet to the lighthouse.
    #"10.0.0.0/8": true

  # advertise_addrs are routable addresses that will be included along with
  # discovered addresses to report to the lighthouse, the format is "ip:port".
  # `port` can be `0`, in which case the actual listening port will be used in
  # its place, useful if `listen.port` is set to 0.
  # This option is mainly useful when there are static ip addresses the host
  # can be reached at that nebula can not typically discover on its own.
  # Examples being port forwarding or multiple paths to the internet.
  #advertise_addrs:
    #- "1.1.1.1:4242"
    #- "1.2.3.4:0" # port will be replaced with the real listening port


# Configure the listening address for the nebula daemon.
listen:
  # Specify the IP addresses that nebula will listen on.
  # The default is 0.0.0.0 (all IPv4 addresses on this host)
  # To listen on all IPv4 and IPv6 addresses, use "[::]"
  host: 0.0.0.0
  # Specify the port that nebula will listen on.
  # For a lighthouse node, the port should not be set to 0, otherwise the port
  # will be randomized, thus other nodes won't be able to connect to it.
  # For any other node, you can specify a port here, or you can set it to 0,
  # such that a port will be dynamically assigned (this is recommended for
  # roaming nodes).
  # Default is 4242
  port: 4242

  # Sets the max number of packets to pull from the kernel for each syscall
  # (on systems that support recvmmsg).
  # Default is 64 (reload not supported)
  #batch: 64
  # Configure socket buffers for the udp side (outside), leave unset to use the
  # system defaults. Values will be doubled by the kernel.
  # Default is net.core.rmem_default and net.core.wmem_default
  # (/proc/sys/net/core/rmem_default and /proc/sys/net/core/rmem_default)
  # Maximum is limited by available memory. SO_RCVBUFFORCE and SO_SNDBUFFORCE
  # are used to avoid having to raise the system wide max (net.core.rmem_max
  # and net.core.wmem_max)
  #read_buffer: 10485760
  #write_buffer: 10485760

  # Controls whether nebula should reply to packets it has no tunnel for, with
  # a "recv_error" packet. This helps speed up reconnection in case the nebula
  # daemon on either side of the tunnel did not shut down cleanly.
  # However, this can also be abused to discover if nebula is running on a host.
  # Valid values are:
  # always: always send "recv_error" packets
  # never: never send "recv_error" packets
  # private: only send "recv_error" packets to nodes with private routable IPs
  # Default is always (reload is supported)
  #send_recv_error: always


# The number of thread pairs to run on the tun device and UDP queues. If this
# is greater than 1, then IFF_MULTI_QUEUE will be set on the tun device and
# SO_REUSEPORT will be set on the UDP socket, in order to allow multiple queues.
# This option is only supported on Linux.
# Default is 1
#routines: 1


punchy:
  # Continues to punch inbound/outbound at a regular interval to avoid
  # expiration of firewall nat mappings
  # Default is false
  punch: true

  # If respond is true, a node you are trying to reach will connect back out to
  # you if your hole punching fails. This is extremely useful if one node is
  # behind a difficult NAT, such as a symmetric NAT.
  # Default is false
  #respond: true

  # delays a punch response for misbehaving NATs, only valid if respond is true
  # Default is 1s
  #delay: 1s


# Cipher allows you to choose between the available ciphers for your network.
# Options are chachapoly or aes
# IMPORTANT: this value must be identical on ALL NODES/LIGHTHOUSES.
# We do not/will not support use of different ciphers simultaneously!
#cipher: chachapoly


# Preferred ranges is used to hint about the local network ranges, which
# speeds up discovering the fastest path to a network adjacent nebula node.
# NOTE: the previous option "local_range" only allowed definition of a single
# range and has been deprecated for "preferred_ranges"
#preferred_ranges: ["172.16.0.0/24"]


# sshd can expose informational and administrative functions via ssh
#sshd:
  # Toggles the feature
  #enabled: true
  # Host and port to listen on, port 22 is not allowed for your safety
  #listen: 127.0.0.1:2222
  # A file containing the ssh host private key to use
  # A decent way to generate one:
  # ssh-keygen -t ed25519 -f ssh_host_ed25519_key -N "" < /dev/null
  #host_key: ./ssh_host_ed25519_key
  # A file containing a list of authorized public keys
  #authorized_users:
    #- user: steeeeve
      # keys can be an array of strings or single string
      #keys:
        #- "ssh public key string"


# EXPERIMENTAL: relay support for networks that can't establish direct
# connections.
relay:
  # Relays are a list of Nebula IP's that peers can use to relay packets to me.
  # IPs in this list must have am_relay set to true in their configs, otherwise
  # they will reject relay requests.
  #relays:
    #- 192.168.100.1
    #- <other Nebula VPN IPs of hosts used as relays to access me>
  # Set am_relay to true to permit other hosts to list my IP in their relays
  # config.
  # Default is false
  am_relay: false
  # Set use_relays to false to prevent this instance from attempting to
  # establish connections through relays.
  # Default is true
  use_relays: true


# Configure the private interface.
# Note: the node's IP address is baked into the nebula certificate.
tun:
  # When tun is disabled, a lighthouse can be started without a local tun
  # interface (and therefore without root).
  disabled: false
  # Name of the device. If not set, a default will be chosen by the OS.
  # For macOS: if set, must be in the form `utun[0-9]+`.
  # For FreeBSD: Required to be set, must be in the form `tun[0-9]+`.
  dev: nebula1
  # Toggles forwarding of local broadcast packets, the address of which
  # depends on the ip/mask encoded in pki.cert
  drop_local_broadcast: false
  # Toggles forwarding of multicast packets
  drop_multicast: false
  # Sets the transmit queue length, if you notice lots of transmit drops on
  # the tun it may help to raise this number.
  # Default is 500
  tx_queue: 500
  # Default MTU for every packet.
  # Default is 1300, a safe setting for internet based traffic
  mtu: 1300
  # Route based MTU overrides, if you have known vpn ip paths that can support
  # larger MTUs you can increase/decrease them here.
  routes:
    #- mtu: 8800
    #  route: 10.0.0.0/16
  # Unsafe routes allows you to route traffic over nebula to non-nebula nodes.
  # Avoid unsafe routes unless you have hosts/services that cannot run nebula.
  # NOTE: The nebula certificate of the "via" node *MUST* have the "route"
  # defined as a subnet in its certificate.
  # `mtu` will default to tun interface's mtu if this option is not specified.
  # `metric` will default to 0 if this option is not specified.
  unsafe_routes:
    #- route: 172.16.1.0/24
    #  via: 192.168.100.99
    #  mtu: 1300
    #  metric: 100


# TODO
# Configure logging level
logging:
  # panic, fatal, error, warning, info, or debug.
  # Default is info
  level: info
  # json or text formats currently available.
  # Default is text
  format: text
  # Disable timestamp logging. useful when output is redirected to logging
  # system that already adds timestamps.
  # Default is false
  #disable_timestamp: true
  # timestamp format is specified in Go time format, see:
  #     https://golang.org/pkg/time/#pkg-constants
  # default when `format: json`: "2006-01-02T15:04:05Z07:00" (RFC3339)
  # default when `format: text`:
  #     when TTY attached: seconds since beginning of execution
  #     otherwise: "2006-01-02T15:04:05Z07:00" (RFC3339)
  # As an example, to log as RFC3339 with millisecond precision, set to:
  #timestamp_format: "2006-01-02T15:04:05.000Z07:00"


#stats:
  #type: graphite
  #prefix: nebula
  #protocol: tcp
  #host: 127.0.0.1:9999
  #interval: 10s

  #type: prometheus
  #listen: 127.0.0.1:8080
  #path: /metrics
  #namespace: prometheusns
  #subsystem: nebula
  #interval: 10s

  # enables counter metrics for meta packets
  #   e.g.: `messages.tx.handshake`
  # NOTE: `message.{tx,rx}.recv_error` is always emitted
  #message_metrics: false

  # enables detailed counter metrics for lighthouse packets
  #   e.g.: `lighthouse.rx.HostQuery`
  #lighthouse_metrics: false


# Handshake Manager Settings
#handshakes:
  # Handshakes are sent to all known addresses at each interval with a linear
  # backoff: Wait try_interval after the 1st attempt, 2 * try_interval after
  # the 2nd, etc, until the handshake is older than timeout.
  # A 100ms interval with the default 10 retries will give a handshake 5.5
  # seconds to resolve before timing out.
  #try_interval: 100ms
  #retries: 20
  # trigger_buffer is the size of the buffer channel for quickly sending
  # handshakes after receiving the response for lighthouse queries
  #trigger_buffer: 64


# Nebula security group configuration
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  # The firewall is default deny. There is no way to write a deny rule.
  # Rules are comprised of a protocol, port, and one or more of host, group,
  # or CIDR.
  # Logical evaluation is roughly:
  # port AND proto AND (ca_sha OR ca_name) AND (host OR group OR groups OR cidr)
  # - port: Takes `0` or `any` as any, a single number `80`, a range `200-901`,
  #         or `fragment` to match second and further fragments of fragmented
  #         packets (since there is no port available).
  #   code: same as port but makes more sense when talking about ICMP
  #         TODO: this is not currently implemented in a way that works, use `any`
  #   proto: `any`, `tcp`, `udp`, or `icmp`
  #   host: `any` or a literal hostname, ie `test-host`
  #   group: `any` or a literal group name, ie `default-group`
  #   groups: Same as group but accepts a list of values. Multiple values are
  #           AND'd together and a certificate would have to contain all groups
  #           to pass
  #   cidr: a CIDR, `0.0.0.0/0` is any.
  #   ca_name: An issuing CA name
  #   ca_sha: An issuing CA shasum

  outbound:
    # Allow all outbound traffic from this node
    - port: any
      proto: any
      host: any

  inbound:
    # Allow icmp between any nebula hosts
    - port: any
      proto: icmp
      host: any

    # Allow tcp/443 from any host with BOTH laptop and home group
    - port: 443
      proto: tcp
      groups:
        - laptop
        - home
